### 대기열 토큰 생성
POST http://localhost:8080/api/v1/waiting-queues
Accept: application/json
Content-Type: application/json

{
  "userId": 1
}

### 대기열 조회
GET http://localhost:8080/api/v1/waiting-queues
Accept: application/json
Content-Type: application/json
QUEUE-TOKEN: a44141db-935b-43e6-afa2-3a3b5f277cf1